// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEJBFW-w57ImKYJOI8x_EGMI6hNeoVkVQ',
    appId: '1:901912921019:web:543ef94ca966f297a7ba9e',
    messagingSenderId: '901912921019',
    projectId: 'smart-attendance-system-70d79',
    authDomain: 'smart-attendance-system-70d79.firebaseapp.com',
    databaseURL: 'https://smart-attendance-system-70d79-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-attendance-system-70d79.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF10cAb10f23bchd7YjQpoufXD179Orxo',
    appId: '1:901912921019:android:5ca555cf30a4f5f6a7ba9e',
    messagingSenderId: '901912921019',
    projectId: 'smart-attendance-system-70d79',
    databaseURL: 'https://smart-attendance-system-70d79-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-attendance-system-70d79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf_cWwFKGZdzfQDl7aVkHGllk928EAgJo',
    appId: '1:901912921019:ios:f906265888d35165a7ba9e',
    messagingSenderId: '901912921019',
    projectId: 'smart-attendance-system-70d79',
    databaseURL: 'https://smart-attendance-system-70d79-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-attendance-system-70d79.firebasestorage.app',
    iosBundleId: 'com.example.studentAttendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf_cWwFKGZdzfQDl7aVkHGllk928EAgJo',
    appId: '1:901912921019:ios:f906265888d35165a7ba9e',
    messagingSenderId: '901912921019',
    projectId: 'smart-attendance-system-70d79',
    databaseURL: 'https://smart-attendance-system-70d79-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-attendance-system-70d79.firebasestorage.app',
    iosBundleId: 'com.example.studentAttendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEJBFW-w57ImKYJOI8x_EGMI6hNeoVkVQ',
    appId: '1:901912921019:web:e9bf1fe4cec860e5a7ba9e',
    messagingSenderId: '901912921019',
    projectId: 'smart-attendance-system-70d79',
    authDomain: 'smart-attendance-system-70d79.firebaseapp.com',
    databaseURL: 'https://smart-attendance-system-70d79-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-attendance-system-70d79.firebasestorage.app',
  );

}